---
version: '3.9'
services:
  tradingview-webhook-bot:
    build: .
    container_name: tradingview-webhook-bot
    ports:
        - '80:8080'
    restart: unless-stopped
    command: [
      "uvicorn",
      "main:app",
      "--workers", "4",
      "--host", "0.0.0.0",
      "--port", "8080",
      '--root-path', '/']